name: Front-end Test on Push

on:
  push:

jobs:
  install-and-verify-syntax:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: npx cypress info
      - run: npm run lint
      - run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: My-build
          if-no-files-found: error
          path: dist

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-ci
          wait-on: "http://localhost:8081"
          wait-on-timeout: 500
          record: true
          browser: chrome
          parallel: true
        env:
          CYPRESS_RECORD_KEY: "ca3f404b-1d73-4ff2-8b09-8a931fb57358"
          VUE_APP_BACKEND_HOST: "https://tradeshare-backend-for-test.herokuapp.com/api/v1"
          CI: ""
